{
 "title": "SBC monitoring",
 "description": "Session Border Controller monitoring",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "host",
    "query": "SHOW TAG VALUES FROM sbc WITH KEY=host"
   }
  ]
 },
 "panels": [
  {
   "title": "SIP trunk Carrier A (sbc-1)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "proxy_set",
     "query": "SELECT last(\"status_code\") FROM \"proxy_set\" WHERE (\"host\" = '13.66.159.172' AND \"name\" = 'PxySet_Teams') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "status_code" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "PxySet_NewtechTeams" }
     ]
    }
   ]
  },
  {
   "title": "CPU utilization",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sbc",
     "select": [
      [
       { "params": [ "cpu" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Resource Allocation Error Calls",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 10, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "usage",
     "select": [
      [
       {
        "params": [
         "calls_terminated_resource_allocation"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Users calls distribution(CARRIER-A)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "alias": "$tag_callee",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "last_calls",
     "query": "SELECT count(\"session_id\") FROM \"last_calls\" WHERE (\"ip_group\" = 'IPG_SipTrunkLumen'  OR \"ip_group\" = 'IPG_TeamsBancoDeChile') AND $timeFilter GROUP BY time($interval), \"callee\"\n",
     "select": [
      [
       { "params": [ "session_id" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "SBC" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "13.66.159.172" }
     ]
    }
   ]
  },
  {
   "title": "Established Calls",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 10, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "usage",
     "select": [
      [
       { "params": [ "established_calls" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Avg. RTD",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 10, "y": 4 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sbc",
     "select": [
      [
       { "params": [ "avg_rtd" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "SIP trunk Carrier B (sbc-2)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "proxy_set",
     "query": "SELECT last(\"status_code\") FROM \"proxy_set\" WHERE (\"host\" = '192.168.0.20' AND \"name\" = 'SipInt_ConexionSBCTeams' ) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "status_code" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "ProxySet_BancoDeChile" }
     ]
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 5 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sbc",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Avg. Jitter",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 10, "y": 6 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sbc",
     "select": [
      [
       { "params": [ "avg_jitter" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Concurrent calls (sbc-1) ",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 10, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sbc",
     "select": [
      [
       { "params": [ "concurrent_calls" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "# Alarms",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "alarms",
     "select": [
      [
       { "params": [ "seq" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Alarms",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 10 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "date" ], "type": "tag" },
      { "params": [ "description" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "severity" ], "type": "tag" },
      { "params": [ "source" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "alarms",
     "select": [
      [
       { "params": [ "seq" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "seq" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Last calls",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "callee" ], "type": "tag" },
      { "params": [ "caller" ], "type": "tag" },
      { "params": [ "direction" ], "type": "tag" },
      { "params": [ "duration" ], "type": "tag" },
      { "params": [ "end_time" ], "type": "tag" },
      { "params": [ "ip_group" ], "type": "tag" },
      { "params": [ "remote_ip" ], "type": "tag" },
      { "params": [ "termination_reason" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "last_calls",
     "query": "SELECT \"session_id\" FROM \"last_calls\" WHERE (\"ip_group\" = 'IPG_DirectRoutingTeams' OR \"ip_group\" = 'IPG_SBCTeams' ) AND $timeFilter GROUP BY \"callee\", \"caller\", \"direction\", \"duration\", \"end_time\", \"ip_group\", \"remote_ip\", \"termination_reason\"",
     "select": [
      [
       { "params": [ "session_id" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ip_group", "operator": "=", "value": "IPG_IPLanMolinosAgro" },
      {
       "condition": "OR",
       "key": "ip_group",
       "operator": "=",
       "value": "IPG_MolinosAgroDirectRoutingTeams"
      },
      { "condition": "OR", "key": "ip_group", "operator": "=", "value": "IPG_DirectRoutingTeams" },
      { "condition": "OR", "key": "ip_group", "operator": "=", "value": "IPG_Martinez   " },
      { "condition": "OR", "key": "ip_group", "operator": "=", "value": "IPG_SipTrunkLumen" }
     ]
    }
   ]
  },
  {
   "title": "Calls Usage Statistics",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Call attempts",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "usage",
     "select": [
      [
       { "params": [ "call_attempts" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Calls abnormally terminated",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "usage",
     "select": [
      [
       {
        "params": [
         "calls_terminated_abnormally_terminated"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "13.66.159.172" }
     ]
    },
    {
     "alias": "Call terminated on busy line",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "usage",
     "select": [
      [
       { "params": [ "calls_terminated_busy_line" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "13.66.159.172" }
     ]
    },
    {
     "alias": "Call terminated on media negotiation",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "usage",
     "select": [
      [
       {
        "params": [
         "calls_terminated_media_negotiation"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "13.66.159.172" }
     ]
    },
    {
     "alias": "Established calls",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "usage",
     "select": [
      [
       { "params": [ "established_calls" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "13.66.159.172" }
     ]
    },
    {
     "alias": "Call attempts",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "usage",
     "select": [
      [
       { "params": [ "call_attempts" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "13.66.159.172" }
     ]
    }
   ]
  },
  {
   "title": "Network connectivity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "RTT MAX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "icmp",
     "query": "SELECT distinct(\"RTT_MAX\") FROM \"icmp\" WHERE (\"host\" = '13.66.159.172') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "RTT_MAX" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "RTT MIN",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "icmp",
     "select": [
      [
       { "params": [ "RTT_MIN" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "13.66.159.172" }
     ]
    },
    {
     "alias": "RTT AVG",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "icmp",
     "select": [
      [
       { "params": [ "RTT_AVG" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "13.66.159.172" }
     ]
    }
   ]
  },
  {
   "title": "RTT avg.",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "icmp",
     "select": [
      [
       { "params": [ "RTT_AVG" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Jitter avg.",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "icmp",
     "select": [
      [
       { "params": [ "RTT_MDEV" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Packet Loss",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 35 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "icmp",
     "select": [
      [
       { "params": [ "PACKET_LOSS" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  }
 ]
}